language: C++
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - sudo apt-get update -q
  - sudo apt-get install graphviz -y

install:
  - pip install tabulate
  - pip install .

script:
  - py.test -v
